version: '3'
services:
  web:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    image: charu97/my-react-app:latest
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    stdin_open: true
    image: charu97/my-react-app:latest
    volumes:
      - /app/node_modules
      - .:/app
    command: ['npm', 'run', 'test']
